blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/Rudra-G-23/Find-My-Joint/blob/main/README.md
    about: Read the project documentation.
  - name: ðŸ’¬ Discussions
    url: https://github.com/Rudra-G-23/Find-My-Joint/discussions
    about: Ask questions or share ideas about FindMyJoint.